personal_website/personal_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profile.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_website/profile/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    # /profile/
    path('', views.home, name='home'),

    # /profile/photography/
    path('photography/', views.photography, name='photography'),

    # /profile/about/
    path('about/', views.about, name='about'),

    # /profile/contact/
    path('contact/', views.contact, name='contact'),

    path('email/', views.email, name='email'),

    path('email/success/', views.success, name='success'),

    path('blog/', views.blog, name='blog'),

    path('blog/<slug>', views.blog_detail, name='blog_detail')

]

personal_website/profile/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

import os
#from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.

# -------------------------------------------------- PHOTO--------------------------------------------------------------

# def get_photo_path():
#     return str(os.path.abspath(os.path.join(os.path.dirname(__file__))))

class Photo(models.Model):

    photo_name        = models.CharField(
                        max_length=200,
                        null=True,
                        blank=True,
                        unique=True,
                        help_text="Title of photo")

    photo_path        = models.FilePathField(
                        unique=True,
                        max_length=128,
                        path="G:\All Pics & Videos\Witney",
                        #path=settings.FILE_PATH_FIELD_DIRECTORY,
                        help_text="Path to photo stored on disk")


    photo_format      = models.CharField(
                        max_length=5,
                        null=True,
                        blank=True,
                        help_text="File format of photo")

    photo_size_MB     = models.CharField(
                        max_length=10,
                        null=True,
                        blank=True,
                        help_text="File size of photo on disk in MB")

    photo_created     = models.DateTimeField(
                        null=True,
                        blank=True,
                        help_text="File size of photo on disk in MB")

    photo_location    = models.CharField(
                        max_length=100,
                        null=True,
                        blank=True,
                        help_text="Location where photo was captured")

    photo_description = models.CharField(
                        max_length=200,
                        null=True,
                        blank=True,
                        help_text="Photo tags separated by a semicolon")

    photo_slug        = models.SlugField(
                        max_length=200,
                        unique=True,
                        help_text="Uses the title of a photo to generate a URL slug")

    # objects = PhotoQuerySet.as_manager()  # converts queryset into manage form

    class Meta:
        verbose_name_plural = "Photographs"
        ordering = ["-photo_created"]

    def __str__(self):
        return self.photo_name

# -------------------------------------------------- VIDEO -------------------------------------------------------------

def get_video_path():
    return os.path.abspath(os.path.join(os.path.dirname(__file__), 'data'))

class Video(models.Model):

    video_name        = models.CharField(
                        max_length=200,
                        null=True,
                        blank=True,
                        unique=True,
                        help_text="Title of video")

    video_path        = models.FilePathField(
                        unique=True,
                        max_length=128,
                        path="G:\All Pics & Videos\Witney",
                        help_text="Path to video stored on disk")

    video_format      = models.CharField(
                        max_length=5,
                        null=True,
                        blank=True,
                        help_text="File format of video written as '.' followed by the file extension e.g. '.mov'")

    video_size_MB     = models.CharField(
                        max_length=10,
                        null=True,
                        blank=True,
                        help_text="File size of video on disk in MB")

    video_created     = models.DateTimeField(
                        max_length=10,
                        null=True,
                        blank=True,
                        help_text="Date and time when video was created")

    video_location    = models.CharField(
                        max_length=100,
                        null=True,
                        blank=True,
                        help_text="Primary location where video was captured")

    video_description = models.CharField(
                        max_length=200,
                        null=True,
                        blank=True,
                        help_text="Video tags separated by a semicolon")

    video_slug        = models.SlugField(
                        max_length=200,
                        unique=True,
                        help_text="Uses the title of a video to generate a URL slug")

    class Meta:
        ordering = ["-video_created"]

    def __str__(self):
        return self.video_name

# -------------------------------------------------- BLOG --------------------------------------------------------------

class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)

class Entry(models.Model):
    title     = models.CharField(
                max_length=200,
                help_text="Title of blog entry limited to 200 characters")

    topic     = models.CharField(
                max_length=100,
                help_text="The general topic of the blog entry")

    body      = RichTextUploadingField(
                null=True,
                blank=True)
                # config_name='extraPlugins',
                # external_plugin_resources=[('youtube',
                #                             'profile/static/plugins/youtube/',
                #                             'plugin.js')])

    publish   = models.BooleanField(
                default=True,
                help_text="Check box to publish blog entry. Leave unchecked to avoid publishing blog entry")

    slug      = models.SlugField(
                max_length=200,
                unique=True,
                help_text="Uses the title of an article to generate a URL slug")

    created   = models.DateTimeField(
                auto_now_add=True,
                help_text="Creation date of blog entry")

    modified  = models.DateTimeField(
                auto_now=True,
                help_text="Date and time when blog post was last modified")

    objects   = EntryQuerySet.as_manager() # converts queryset into manage form

    class Meta:
        verbose_name = "Blog Entry"
        verbose_name_plural = "Blog Entries"
        ordering = ["-created"]

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("entry_detail", kwargs={'slug': self.slug})

personal_website/profile/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.mail import EmailMessage
from django.urls import reverse
from django.conf import settings

from django.core.paginator import Paginator

from .forms import ContactForm
from . import views, urls, models
from .models import Entry

import os

# Create your views here.
def home(request):
    return render(request, 'profile/home.html')

def photography(request):
    # insert the path to your directory
    path = "G:\\All Pics & Videos\\Witney"
    img_list = os.listdir(path)
    # return render_to_response('gallery.html', {'images': img_list})
    return render(request, 'profile/photography.html', {'images': img_list})

def about(request):
    return render(request, 'profile/about.html')

def contact(request):
    return render(request, 'profile/contact.html')#, context)

def email(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['taylor.graham@zohomail.eu'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect('success')
    return render(request, 'profile/email.html', {'form': form})

def success(request):
    return render(request, 'profile/success.html')

def blog(request):
    posts = Entry.objects.all()
    paginator = Paginator(posts, 3)
    page = request.GET.get('page')
    #?page=2
    posts = paginator.get_page(page)

    return render(request, 'profile/blog.html', {'posts': posts})

def blog_detail(request, slug):
    post = get_object_or_404(Entry, slug=slug)
    return render(request, 'profile/blog_detail.html', {'post': post})

personal_website/profile/templates/profile/about.html
{% extends "profile/base.html" %}
{% load staticfiles %}
{% block content %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'profile:home' %}" aria-hidden="true" width="100%"> Graham Taylor</a>

        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'profile:home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'profile:about' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; About
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'profile:blog' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Blog
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'profile:photography' %}">
                        <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>&nbsp; Photography
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'profile:contact' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Contact
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1200px-Flag_of_the_Netherlands.svg.png" aria-hidden="true" height="14">&nbsp; NL
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="#">
                        <img src="https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/1280px-Flag_of_the_United_Kingdom.svg.png" aria-hidden="true" height="12">&nbsp; UK
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

<style>
div.centre {
        text-align: center;
        font-size: 6px;

}

div.justify-centre {
        text-align: center;

}

div.column-far-left {
        position: absolute;
        left: 500;
        right: 1000;
}

div.column-left {
        position: absolute;
        left: 1020;
        right: 450;
}

div.black {
        color: black;

}

.text-orange {
        color: orange;

}

.text-white {
        color: white;

}

div.nametext {
        color: black;
        font-family: 'Inconsolata', monospace;
        font-size: 80px;
}

div.headertext {
        color: orange;
        font-family: 'Wire One', sans-serif;
        font-size: 75px;
}

table.centre {
        margin-left: auto;
        margin-right: auto;
}

table.table1 {
        width: 50%;

}

table.table2 {
        margin-top: 50px;

}

th {
  text-align: left;
  vertical-align: top;

}

td {
  text-align: left;
  padding-top: 20px;
  padding-bottom: 20px;
  vertical-align: top;

}

.typewriter {
  overflow: hidden; /* Ensures the content is not revealed until the animation */
  border-right: .15em solid orange; /* The typwriter cursor */
  white-space: nowrap; /* Keeps the content on a single line */
  margin: 0 auto; /* Gives that scrolling effect as the typing happens */
  letter-spacing: .15em; /* Adjust as needed */
  animation:
    typing 2.5s steps(12, end),
    blink-caret 0.75s step-end infinite;
}

/* The typing effect */
@keyframes typing {
  from { width: 0 }
  to { width: 35% }
}

/* The typewriter cursor effect */
@keyframes blink-caret {
  from, to { border-color: transparent }
  50% { border-color: orange; }
}

.arrow {
    background: orange;
	color: black;
}

.scroll-indicator {
	position: absolute;
	left: 95%;
	font-size: 50px;

	-webkit-animation: bounce 1s infinite;
	animation: bounce 1s infinite;
}

@-webkit-keyframes bounce {
	 0% { top: 88%; }
	 50%   { top: 89%; }
	 100% { top: 88%; }
}

@keyframes bounce {
	 0% { top: 88%; }
	 50%   { top: 89%; }
	 100% { top: 88%; }
}



#wrapper {
    margin-left:auto;
    margin-right:auto;
    width:2000px;
}


</style>


<div class="centre nametext typewriter">
    <span>Graham Taylor</span>
</div>
<div class ="centre black">
   <br>______________________________________________________________________________________________________________________________________________________________________________________________________________</br>
</div>
<div class="centre headertext">
    <span>Botanist + Data Scientist + Programmer</span>
    <br>
    <img src="{% static "profile/images/Namaqualand_flower.jpg" %}" style="position: relative; left: 0; width: 100%;">
</div>
<div class="scroll-indicator fa fa-chevron-down arrow" style="position: fixed;"></div>


<div class="w3-section w3-2019-sweet-corn" style="position: relative; top: -20px; left: 0px; height: auto;">
    <div class="justify-centre headertext">
        <p></p>
        <p>About</p>
    </div>
    <div class="justify-centre">
        <div class="w3-container">
            <img src="{% static "profile/images/me.png" %}" class="w3-circle" alt="Profile Picture" style="width: 22%">
        </div>
        <br>
        <br>
    </div>

    <div class="" style="padding-bottom: 180px; margin-left: 25%; margin-right: 25%;">
        <br>
        <p><b>Welcome to my digital portfolio.</b></p>
        <p>This is where I am hoping to share experiences and some projects that I am working on with the online community.</p>
        <p>A little bit about me. I spent much of my early childhood growing up in South Africa, and have since left sunny African shores to pursue further study and a new life abroad. Much of the memories
            of growing up in Africa are remembered fondly and I hope one day to return! I have made many new friends and now family in Europe, specifically the Netherlands, where I studied and more recently in England where I am currently based. </p>

        <p>I am enthusiastic about learning and developing new things</p>

        <p>Please feel free to explore my website.</p>

        <p>Sincerely,
            <br>
        Graham</p>
    </div>
</div>
    <!--<p>Research is to see what everybody else has seen, and to think what nobody else has thought. Albert Szent-Gyorgyi</p>-->

{% endblock content %}

personal_website/profile/templates/profile/contact.html
<!--Loads the path to your static files -->
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'profile/home_style.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'profile/breadcrumbs.css' %}"/>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-2019.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-2018.css">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Cinzel|Inconsolata:400,700|Satisfy|Ubuntu|Wire+One" rel="stylesheet">
<link rel="icon" type="image/png" href="{% static 'profile/images/favicon-32x32_orange.png' %}"/>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'profile:home' %}" aria-hidden="true" width="100%"> Graham Taylor</a>

        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'profile:home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'profile:about' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; About
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'profile:blog' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Blog
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'profile:photography' %}">
                        <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>&nbsp; Photography
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'profile:contact' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Contact
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1200px-Flag_of_the_Netherlands.svg.png" aria-hidden="true" height="14">&nbsp; NL
                    </a>
                </li>
            </ul>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="#">
                        <img src="https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/1280px-Flag_of_the_United_Kingdom.svg.png" aria-hidden="true" height="12">&nbsp; UK
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

<style>

div.headertext {
        color: orange;
        font-family: 'Wire One', sans-serif;
        font-size: 75px;
}

div.centre {
        text-align: center;
        font-size: 75px;

}

.content {
  max-width: 500px;
  margin: auto;

}

</style>

<div class="w3-section w3-2019-sweet-corn" style="position: absolute; top: 35px; left: 0px; height: 1500; width: 100%;">
    <div class="centre headertext">
            <span>Contact me</span>
    </div>
        <!--<img src="{% static "profile/images/Bee.jpg" %}" style="width:100%; position: absolute; top: 290; left: 0; ">-->
            <p>I am currently based in Oxfordshire, the United Kingdom. I am open to collaborating on new data-related projects, photography or videography.
                Feel free to contact me if you wish to make something happen. I can be reached on:</p>
            <br>

    <h1>Contact Us</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
        <button type="submit">Send</button>
    </div>
</form>

</div>
<!--<div class="content">-->
    <!--<a href="" target=blank>-->
        <!--<img src="{% static "profile/images/Yahoo2.png" %}" alt="Yahoo Mail" aria-hidden="true" height="50">-->
    <!--</a>-->
    <!--<span>&nbsp;&nbsp;&nbsp;</span>-->
    <!--<a href="https://bitbucket.org/g_taylor2/" target=blank>-->
        <!--<img src="{% static "profile/images/Bitbucket2.png" %}" alt="Bitbucket" aria-hidden="true" height="30">-->
    <!--</a>-->
    <!--<span>&nbsp;&nbsp;&nbsp;&nbsp;</span>-->
     <!--<a href="https://www.linkedin.com/in/graham-taylor-4901322a/" target=blank>-->
         <!--<img src="{% static "profile/images/LinkedIn_black.png" %}" alt="LinkedIn" aria-hidden="true" height="30">-->
     <!--</a>-->
<!--</div>-->

<!-- This is where the footer begins -->
<nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container-fluid">
        <ul class="nav navbar-nav navbar-left">
            <li class="">
                <a href="">
                    <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span>&nbsp; 2018 - {% now "Y" %}. All rights reserved.
                </a>
            </li>
            <li class="">
                <a href="http://www.djangoproject.com/" target=blank>
                    <img src="https://www.djangoproject.com/m/img/badges/djangomade124x25_grey.gif" border="0" alt="Made with Django" title="Made with Django.">
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="https://bitbucket.org/g_taylor2/" target=blank>
                    <img src="{% static "profile/images/Bitbucket_white.png" %}" alt="Bitbucket" aria-hidden="true" height="13">
                </a>
            </li>
            <li class="">
                <a href="https://www.linkedin.com/in/graham-taylor-4901322a/" target="blank">
                    <img src="{% static "profile/images/LinkedIn.png" %}" alt="LinkedIn" aria-hidden="true" height="16.5">
                </a>
            </li>
        </ul>

    </div>
</nav>

</div>

personal_website/profile/templates/profile/contact2.html
<!--Loads the path to your static files -->
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'profile/home_style.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'profile/breadcrumbs.css' %}"/>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-2019.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-2018.css">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Cinzel|Inconsolata:400,700|Satisfy|Ubuntu|Wire+One" rel="stylesheet">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">

<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'profile:home' %}" aria-hidden="true" width="100%"> Graham Taylor</a>

        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'profile:index' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'profile:about' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; About
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'profile:addspecies' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Blog
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>&nbsp; Photography
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'profile:contact2' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Contact
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1200px-Flag_of_the_Netherlands.svg.png" aria-hidden="true" height="14">&nbsp; NL
                    </a>
                </li>
            </ul>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="#">
                        <img src="https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/1280px-Flag_of_the_United_Kingdom.svg.png" aria-hidden="true" height="12">&nbsp; UK
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>


</head>

<style>

div.headertext {
        color: orange;
        font-family: 'Wire One', sans-serif;
        font-size: 75px;
}

div.centre {
        text-align: center;
        font-size: 75px;

}

.content {
  max-width: 500px;
  margin: auto;

}

</style>

<div class="container-fluid">

 <div class="centre headertext">
    <span>Contact me</span>
    <img src="{% static "profile/images/Bee.jpg" %}" style="width:100%; position: absolute; top: 290; left: 0; ">
 </div>

<p>I am currently based in Oxfordshire, the United Kingdom. I am open to collaborating on new data-related projects, photography or videography.
Feel free to contact me if you wish to make something happen. I can be reached on:</p>
<br>

<div class="content">
    <a href="" target=blank>
        <img src="{% static "profile/images/Yahoo2.png" %}" alt="Yahoo Mail" aria-hidden="true" height="50">
    </a>
    <span>&nbsp;&nbsp;&nbsp;</span>
    <a href="https://bitbucket.org/g_taylor2/" target=blank>
        <img src="{% static "profile/images/Bitbucket2.png" %}" alt="Bitbucket" aria-hidden="true" height="30">
    </a>
    <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
     <a href="https://www.linkedin.com/in/graham-taylor-4901322a/" target=blank>
         <img src="{% static "profile/images/LinkedIn_black.png" %}" alt="LinkedIn" aria-hidden="true" height="30">
     </a>
</div>


<!-- This is where the footer begins -->
<nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container-fluid">
        <ul class="nav navbar-nav navbar-left">
            <li class="">
                <a href="">
                    <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span>&nbsp; 2018 - {% now "Y" %}. All rights reserved.
                </a>
            </li>
            <li class="">
                <a href="http://www.djangoproject.com/" target=blank>
                    <img src="https://www.djangoproject.com/m/img/badges/djangomade124x25_grey.gif" border="0" alt="Made with Django" title="Made with Django.">
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="https://bitbucket.org/g_taylor2/" target=blank>
                    <img src="{% static "profile/images/Bitbucket_white.png" %}" alt="Bitbucket" aria-hidden="true" height="12">
                </a>
            </li>
            <!--<li class="">-->
                <!--<a href="https://www.facebook.com/graham.j.taylor.3/" target=blank>-->
                    <!--<img src="{% static "home/images/facebook.png" %}" alt="Facebook" aria-hidden="true" height="17">-->
                <!--</a>-->
            <!--</li>-->
            <li class="">
                <a href="https://www.linkedin.com/in/graham-taylor-4901322a/" target="blank">
                    <img src="{% static "profile/images/LinkedIn.png" %}" alt="LinkedIn" aria-hidden="true" height="16">
                </a>
            </li>
        </ul>

    </div>
</nav>