oxfordmicrogreens/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView

app_name = 'shop'

urlpatterns = [
    # /shop/
    path('', views.product_list, name='product_list'),

    # /shop/home/
    path('home/', views.home, name='home'),

    # /shop/about/
    path('about/', views.about, name='about'),

    # /shop/contact/
    path('contact/', views.contact, name='contact'),

    # /shop/email/
    path('email/', views.email, name='email'),

    # /shop/email/success/
    path('email/success/', views.success, name='success'),

    # /shop/blog/
    path('blog/', views.blog, name='blog'),

    # /shop/blog/<slug>/
    path('blog/<slug>', views.blog_detail, name='blog_detail'),

    # /shop/delivery/
    path('delivery/', views.delivery, name='delivery'),

    # /shop/team/
    path('team/', views.team, name='team'),

    # /shop/products/microgreens/
    path('products/microgreens/', views.microgreens, name='microgreens'),

    # /shop/products/microgreens/
    path('products/microgreens/<slug>', views.microgreen_detail, name='microgreen_detail'),

    # /shop/products/growth-cabinets/
    path('products/growth-cabinets/', views.growth_cabinets, name='growth_cabinets'),

    # /shop/register/
    path('register/', views.register, name='register'),

    # /shop/profile/
    path('profile/', views.profile, name='profile'),

    # /shop/profile/edit/
    path('profile/edit/', views.edit_profile, name='edit_profile'),

    # /shop/profile/change-password/
    path('profile/change-password/', views.change_password, name='change_password'),

    # /shop/login/
    path('login/', LoginView.as_view(template_name='shop/login.html'), name="login_user"),

    # /shop/login_successful/
    path('login_successful/', views.login_successful, name='login_successful'),

    # /shop/logout/
    #path('logout/', views.logout_user, name='logout_user'),

# /shop/login_successful/
    path('test/', views.test, name='test'),

    # '/'
    path('', include('django.contrib.auth.urls'))

]

oxfordmicrogreens/shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">

{% include "shop/header.html" %}
{% include "shop/scripts.html" %}

<body class="Site">
<main class="Site-content">
    {% block content %}
    {% endblock content %}
</main>
</body>

{% include "shop/footer.html" %}

</html>

oxfordmicrogreens/shop/templates/shop/blog.html
<header>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</header>

{% extends "shop/base.html" %}
{% load staticfiles %}
{% block content %}

<p class="justify-centre" style="background-color:gray; color: white; margin-top:10px; padding-top: 2px; padding-bottom: 2px;">Free U.K. Mainland Shipping</p>
<nav class="navbar navbar-default navbar-expand-lg" style="background-color: white; padding-left: 40px;">
<!--    <nav class="navbar navbar-default" style="background-color: white">-->

    <div class="container-fluid">

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="" aria-hidden="true"><span><img src="{% static "shop/images/oxford_logo2.png" %}" height=50; style="position: relative; top:-15px";"/></span><span style="position: relative; top:-15px; right: -3px;"> Oxford Micro</span><span style="color: green; position: relative; top:-15px; right: -3px;">Farm</span></a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'shop:home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                    </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
                </li>
                <li class="nav-item">
                    <a href="{% url 'shop:about' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Our Story
                    </a>
                </li>
                <li class="nav item">
                    <a href="{% url 'shop:team' %}">
                        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>&nbsp; Our Team
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'shop:blog' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Blog
                    </a>
                </li>
                <li class="nav item">
                    <a href="{% url 'shop:delivery' %}">
                        <span class="glyphicon glyphicon-send" aria-hidden="true"></span>&nbsp; Delivery
                    </a>
                </li>
                <li class="nav item">
                    <a href="{% url 'shop:contact' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Contact Us
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                    <a href="#">
                        <img src="{% static "shop/images/Netherlands_Flag.png" %}" aria-hidden="true" height="14">&nbsp; NL
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="#">
                        <img src="{% static "shop/images/UK_Flag.png" %}" aria-hidden="true" height="12">&nbsp; UK
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'shop:delivery' %}">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;Cart
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                     {% if request.user.is_active %}
                         <a href="{% url 'shop:profile' %}">
                     {% else %}
                         <a href="{% url 'shop:register' %}">
                     {% endif %}
                         {% if request.user.is_authenticated %}
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Welcome, <b>{{ request.user.username }}</b></a>
                         {% else %}
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Account</a>
                         {% endif %}
                 </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                     {% if request.user.is_authenticated %}
                         <a href="{% url 'shop:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a>
                     {% else %}
                     {% endif %}
                 </li>
            </ul>

        </div>
    </div>
</nav>

<style>

.single-column {
        position: relative;
        margin-left: 25%;
        margin-right: 25%;
}

.bottom {
    position: relative;
    text-align: center;
}

.heading {
    position: relative;
    text-align: center;
}

</style>

<br>
<div class="justify-centre nametext">
     <span>Oxford Micro</span><span style="color:green;">Farm</span>
</div>
<div class ="justify-centre black">
    <p>_______________________________________________________________________________________________________________________________________</p>
</div>
<br>
<div class="justify-centre headertext typewriter">
    <span>Blog</span>
    <br>
</div>

<div class="w3-section w3-2019-sweet-corn" style="position: relative; top: 0px; left: 0px; height: auto;">
    <br>
    <h3 class="single-column" style="text-align: center;">A very warm welcome to our blog! Here we share the latest trends in the horticultural marketspace</h3>
    <br>

    {% for post in posts %}

    <div class="single-column">
        <h2 class="justify-centre" style="color: green;"><a href="/shop/blog/{{ post.slug }}"><strong>{{ post.title }}</strong></a></h2>
        <h6><strong>Tags: </strong>{{ post.topic }}</h6>
        <h6><strong>Created: </strong> {{ post.created }} GMT; <strong>Last modified: </strong>{{ post.modified }} GMT</h6>
        <p>{{ post.body | truncatechars:500 | safe }}</p>
        <br>
    </div>

    {% endfor %}

    <div class="heading justify-centre">
        <br>
        {% if posts.has_previous %}
            <a href="?page=1"><<</a>
            <a href="?page={{ posts.previous_page_number }}" style="left: 50%;"><</a>

        {% endif %}

        {% for num in posts.paginator.page_range %}
            {% if posts.number == num %}
                <strong>{{ num }}</strong>
            {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
                {{ num }}
            {% endif %}

        {% endfor %}

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">></a>
            <a href="?page={{ posts.paginator.num_pages }}">>></a>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        {% endif %}

    </div>
</div>

{% endblock content %}

oxfordmicrogreens/shop/templates/shop/change_password.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}

<p class="justify-centre" style="background-color:gray; color: white; margin-top:10px; padding-top: 2px; padding-bottom: 2px;">Free U.K. Mainland Shipping</p>
<nav class="navbar navbar-default" style="background-color: white; padding-left: 40px;">
<!--    <nav class="navbar navbar-default" style="background-color: white">-->

    <div class="container-fluid">

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="" aria-hidden="true"><span><img src="{% static "shop/images/oxford_logo2.png" %}" height=50; style="position: relative; top:-15px";"/></span><span style="position: relative; top:-15px; right: -3px;"> Oxford Micro</span><span style="color: green; position: relative; top:-15px; right: -3px;">Farm</span></a>

        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'shop:home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:home' %}">
                        <div class="dropdown">
                            <button class="dropbtn" style="position: relative; top: -17px;"><span class="glyphicon glyphicon-grain" aria-hidden="true"></span>&nbsp; Products
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="dropdown-content">
                                <a href="{% url 'shop:microgreens' %}">Microgreens</a>
                                <a href="#">Product B</a>
                                <a href="#">Product C</a>
                                <a href="#">Product D</a>
                            </div>
                        </div>

                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:about' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Our Story
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:team' %}">
                        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>&nbsp; Our Team
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:blog' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Blog
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:delivery' %}">
                        <span class="glyphicon glyphicon-send" aria-hidden="true"></span>&nbsp; Delivery
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:contact' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Contact Us
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <img src="{% static "shop/images/Netherlands_Flag.png" %}" aria-hidden="true" height="14">&nbsp; NL
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="#">
                        <img src="{% static "shop/images/UK_Flag.png" %}" aria-hidden="true" height="12">&nbsp; UK
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'shop:delivery' %}">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;Cart
                    </a>
                </li>
            </ul>
           <ul class="nav navbar-nav navbar-right">
                 <li class="">
                     {% if request.user.is_active %}
                         <a href="{% url 'shop:profile' %}">
                     {% else %}
                         <a href="{% url 'shop:register' %}">
                     {% endif %}
                         {% if request.user.is_authenticated %}
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Welcome, <b>{{ request.user.username }}</b></a>
                         {% else %}
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Account</a>
                         {% endif %}
                 </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                     {% if request.user.is_authenticated %}
                         <a href="{% url 'shop:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a>
                     {% else %}
                     {% endif %}
                 </li>
            </ul>

        </div>
    </div>
</nav>

<style>

.column-left {
        position: relative;
        margin-left: 500px;
        margin-right: 450px;
}

</style>

<br>
<div class="justify-centre nametext">
    <span>Oxford Micro</span><span style="color:green;">Farm</span>
</div>

<div class="justify-centre black">
    <p>_______________________________________________________________________________________________________________________________________</p>
</div>
<br>

<div class="w3-container">
    <h1 style="color: orange">Change Password Information</h1>
    <br>
    <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock content %}

oxfordmicrogreens/shop/templates/shop/contact.html
{% extends "shop/base.html" %}
{% load staticfiles %}
{% block content %}

<p class="justify-centre" style="background-color:gray; color: white; margin-top:10px; padding-top: 2px; padding-bottom: 2px;">Free U.K. Mainland Shipping</p>
<nav class="navbar navbar-default navbar-expand-lg" style="background-color: white; padding-left: 40px;">
<!--    <nav class="navbar navbar-default" style="background-color: white">-->

    <div class="container-fluid">

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="" aria-hidden="true"><span><img src="{% static "shop/images/oxford_logo2.png" %}" height=50; style="position: relative; top:-15px";"/></span><span style="position: relative; top:-15px; right: -3px;"> Oxford Micro</span><span style="color: green; position: relative; top:-15px; right: -3px;">Farm</span></a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'shop:home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Products
                    </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Cabinets</a>
                    <a class="dropdown-item" href="#">Accessories</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
                </li>
                <li class="">
                    <a href="{% url 'shop:about' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Our Story
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:team' %}">
                        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>&nbsp; Our Team
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:blog' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Blog
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:delivery' %}">
                        <span class="glyphicon glyphicon-send" aria-hidden="true"></span>&nbsp; Delivery
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'shop:contact' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Contact Us
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <img src="{% static "shop/images/Netherlands_Flag.png" %}" aria-hidden="true" height="14">&nbsp; NL
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="">
                        <img src="{% static "shop/images/UK_Flag.png" %}" aria-hidden="true" height="12">&nbsp; UK
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'shop:delivery' %}">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;Cart
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                     {% if request.user.is_active %}
                         <a href="{% url 'shop:profile' %}">
                     {% else %}
                         <a href="{% url 'shop:register' %}">
                     {% endif %}
                         {% if request.user.is_authenticated %}
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Welcome, <b>{{ request.user.username }}</b></a>
                         {% else %}
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Account</a>
                         {% endif %}
                 </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                     {% if request.user.is_authenticated %}
                         <a href="{% url 'shop:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a>
                     {% else %}
                     {% endif %}
                 </li>
            </ul>

        </div>
    </div>
</nav>

<br>
<div class="justify-centre nametext">
     <span>Oxford Micro</span><span style="color:green;">Farm</span>
</div>
<div class ="justify-centre black">
    <p>_______________________________________________________________________________________________________________________________________</p>
</div>
<br>

<h1 class="justify-centre" style="color: orange">Contact Us</h1>
<br>
<br>
<form method="post" class="left">
    <fieldset>
        <label></label>{% csrf_token %}
        <label>{{ form.media }}</label>
        <label>{{ form.as_p }}</label>
    </fieldset>

    <div class="form-actions left">
      <button type="submit">Send</button>
    </div>
</form>

{% endblock content %}

oxfordmicrogreens/shop/templates/shop/delivery.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}

<p class="justify-centre" style="background-color:gray; color: white; margin-top:10px; padding-top: 2px; padding-bottom: 2px;">Free U.K. Mainland Shipping</p>
<nav class="navbar navbar-default navbar-expand-lg" style="background-color: white; padding-left: 40px;">
<!--    <nav class="navbar navbar-default" style="background-color: white">-->

    <div class="container-fluid">

        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="" aria-hidden="true"><span><img src="{% static "shop/images/oxford_logo2.png" %}" height=50; style="position: relative; top:-15px";"/></span><span style="position: relative; top:-15px; right: -3px;"> Oxford Micro</span><span style="color: green; position: relative; top:-15px; right: -3px;">Farm</span></a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'shop:home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Products
                    </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Cabinets</a>
                    <a class="dropdown-item" href="#">Accessories</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
                </li>
                <li class="">
                    <a href="{% url 'shop:about' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Our Story
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:team' %}">
                        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>&nbsp; Our Team
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:blog' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Blog
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'shop:delivery' %}">
                        <span class="glyphicon glyphicon-send" aria-hidden="true"></span>&nbsp; Delivery
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'shop:contact' %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Contact Us
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <img src="{% static "shop/images/Netherlands_Flag.png" %}" aria-hidden="true" height="14">&nbsp; NL
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a href="#">
                        <img src="{% static "shop/images/UK_Flag.png" %}" aria-hidden="true" height="12">&nbsp; UK
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'shop:delivery' %}">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;Cart
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                     {% if request.user.is_active %}
                         <a href="{% url 'shop:profile' %}">
                     {% else %}
                         <a href="{% url 'shop:register' %}">
                     {% endif %}
                         {% if request.user.is_authenticated %}
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Welcome, <b>{{ request.user.username }}</b></a>
                         {% else %}
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Account</a>
                         {% endif %}
                 </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                     {% if request.user.is_authenticated %}
                         <a href="{% url 'shop:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a>
                     {% else %}
                     {% endif %}
                 </li>
            </ul>

        </div>
    </div>
</nav>

<style>

.column-left {
        position: relative;
        margin-left: 500px;
        margin-right: 450px;
}

</style>

<br>
<div class="justify-centre nametext">
    <span>Oxford Micro</span><span style="color:green;">Farm</span>
</div>

<div class="justify-centre black">
    <p>_______________________________________________________________________________________________________________________________________</p>
</div>
<br>
<div class="justify-centre headertext typewriter">
    <span>Delivering the goods...</span>
    <br>
</div>

<div class="w3-section w3-2019-sweet-corn" style="position: relative; top: 0px; left: 0px; height: auto;">
    <div class="justify-centre">
        <div class="w3-container">
            <br>
            <img src="{% static "shop/images/shoots4.jpg" %}" class="w3-circle" alt="Sprouts" style="width:400px;">
        </div>
        <br>
        <br>
    </div>

    <div class="justify-centre">
        <br>
        <p style="font-size:20px;"><b>...with a <span style="color: green">Green </span>Delivery Service</b></p>
    </div>

    <p class="column-left">We deliver to all our U.K. based customers. All items are delivered in fully compostable, biodegradeable packaging that can ideally be reused, but also recycled.
    Using our standard delivery service, your order should arrive within 2-3 working days of being placed. Please note that this excludes UK Bank Holidays. Under the standard delivery option, all orders will incur no additional charge.
    For more urgent orders, we offer a next day delivery service at an additional charge of £3.99 incl. VAT.</p>
    <br>
    <br>
    <br>
</div>
    <!--<p>Research is to see what everybody else has seen, and to think what nobody else has thought. Albert Szent-Gyorgyi</p>-->

{% endblock content %}